# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: dark
  color: blue

# SEO
marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'Policy Advocacy in Science and Engineering'
    description: 'LinkInBio for Policy Advocacy in Science and Engineering (PASE).'
    twitter: 'Gator_PASE'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: false
    blox: floating-theme-toggler

# Site footer
footer:
  copyright:
    notice: '© {year} Policy Advocacy in Science and Engineering'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
